name = "Meshing"
uuid = "e6723b4c-ebff-59f1-b4b7-d97aa5274f73"

[deps]
GeometryTypes = "4d00f742-c7ba-57c2-abde-4428a4b178cb"
SIMD = "fdea26ae-647d-5447-a871-4b548cad5224"

[extras]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Profile = "9abbd945-dff8-562f-b5e8-e1ebf5ef1b79"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["ForwardDiff", "LinearAlgebra", "Profile", "Statistics", "Test"]
